export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_STOCK_TO_PORTFOLIO = 'ADD_STOCK_TO_PORTFOLIO';
export const FETCH_STOCKS = 'FETCH_STOCKS';
export const GET_STOCK = 'GET_STOCK';
export const REMOVE_STOCK = 'REMOVE_STOCK';
